In [ ]:
import numpy as np
from Env import GridWorld


DISCOUNT_FACTOR = 1 # 请根据不同的任务使用具体discount_factor


class Agent:
    def __init__(self, env):
        self.env = env
        self.V = np.zeros(env.nS)

    def next_best_action(self, s, V):
        action_values = np.zeros(self.env.nA)
        for a in range(self.env.nA):
            for prob, next_state, reward, done in self.env.P[s][a]:
                action_values[a] += prob * (reward + DISCOUNT_FACTOR * V[next_state])
        return np.argmax(action_values), np.max(action_values)

    def optimize(self): # core method
        THETA = 0.0001
        delta = float("inf")
        round_num = 0

        while delta > THETA:
            # 循环条件：只要最大变化量大于阈值，就继续迭代,
            # 当所有状态的价值变化都很小时（≤0.0001），停止迭代
            delta = 0
            # 重置本轮的最大变化量
            # 准备记录本轮中各状态的变化
            print("\nValue Iteration: Round " + str(round_num))
            print(np.reshape(self.V, self.env.shape))
            for s in range(self.env.nS):
                best_action, best_action_value = self.next_best_action(s, self.V)
                delta = max(delta, np.abs(best_action_value - self.V[s]))
                self.V[s] = best_action_value
            round_num += 1

        policy = np.zeros(self.env.nS)
        for s in range(self.env.nS):
            best_action, best_action_value = self.next_best_action(s, self.V)
            policy[s] = best_action

        return policy


# env = GridWorld()
# agent = Agent(env)
# policy = agent.optimize()
# print("\nBest Policy")
# print(np.reshape([env.get_action_name(entry) for entry in policy], env.shape))

# env = GridWorld(wind_prob=.2)
# agent = Agent(env)
# policy = agent.optimize()
# print("\nBest Policy")
# print(np.reshape([env.get_action_name(entry) for entry in policy], env.shape))


Value Iteration: Round 0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Value Iteration: Round 1
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1.  0. -1.]]

Value Iteration: Round 2
[[-2. -2. -2.]
 [-2. -1. -2.]
 [-1.  0. -1.]]

Value Iteration: Round 3
[[-3. -2. -3.]
 [-2. -1. -2.]
 [-1.  0. -1.]]

Best Policy
[['D' 'D' 'D']
 ['D' 'D' 'D']
 ['R' 'U' 'L']]
